// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB74mPFXrvBRwaxasg7SSCM8-QCM6hCLu4',
    appId: '1:313999103128:web:fc2f3e45a3f26346eeaced',
    messagingSenderId: '313999103128',
    projectId: 'mind-mend-c651a',
    authDomain: 'mind-mend-c651a.firebaseapp.com',
    storageBucket: 'mind-mend-c651a.firebasestorage.app',
    measurementId: 'G-JCGRBHFRZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-tb0EZLfXuDjnXE8i0VJgX6J54Xnz8C0',
    appId: '1:313999103128:android:33a3f251c36e3f7aeeaced',
    messagingSenderId: '313999103128',
    projectId: 'mind-mend-c651a',
    storageBucket: 'mind-mend-c651a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6jb72nYXU2z2dfarm348710Vvw8tcxGI',
    appId: '1:313999103128:ios:aa0975b6bd3d2d15eeaced',
    messagingSenderId: '313999103128',
    projectId: 'mind-mend-c651a',
    storageBucket: 'mind-mend-c651a.firebasestorage.app',
    iosBundleId: 'com.example.mindmend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6jb72nYXU2z2dfarm348710Vvw8tcxGI',
    appId: '1:313999103128:ios:aa0975b6bd3d2d15eeaced',
    messagingSenderId: '313999103128',
    projectId: 'mind-mend-c651a',
    storageBucket: 'mind-mend-c651a.firebasestorage.app',
    iosBundleId: 'com.example.mindmend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB74mPFXrvBRwaxasg7SSCM8-QCM6hCLu4',
    appId: '1:313999103128:web:7291f29c376f02c4eeaced',
    messagingSenderId: '313999103128',
    projectId: 'mind-mend-c651a',
    authDomain: 'mind-mend-c651a.firebaseapp.com',
    storageBucket: 'mind-mend-c651a.firebasestorage.app',
    measurementId: 'G-J19MFXNN4K',
  );
}
